# Generated by Django 4.2.7 on 2023-11-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YouTuber",
            fields=[
                (
                    "channel_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "channel_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "thumbnail_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("comments_disabled", models.BooleanField(blank=True, null=True)),
                ("ratings_disabled", models.BooleanField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="categoryId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube.category",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        db_column="channelId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube.youtuber",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_column="region_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "statistic_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "publishedAt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "trending_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("view_count", models.IntegerField(blank=True, null=True)),
                ("comment_count", models.IntegerField(blank=True, null=True)),
                ("likes", models.IntegerField(blank=True, null=True)),
                ("dislikes", models.IntegerField(blank=True, null=True)),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        db_column="video_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube.video",
                    ),
                ),
            ],
        ),
    ]
