# Generated by Django 4.2.7 on 2023-11-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
