# Generated by Django 4.2.7 on 2023-12-04 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0003_alter_video_category_alter_video_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
    ]
