# Generated by Django 4.2.7 on 2023-12-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0004_remove_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="youtube.video",
            ),
        ),
    ]
